name: "cachix cache"
on:
  pull_request:
  push:
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v15
      with:
        name: ony-boom
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build and push to cachix
      run: |
        nix build .#default --print-build-logs
        cachix push ony-boom ./result
